### ISSUE TITLE
Prep setup.py

### ISSUE THREAD

**Issue by tpn** [ContinuumIO/ctk#2]
Take a look at enversion/enversion/setup.py for an example.

Should be able to `python setup.py install` and get 'ctk' installed and importable in an `import ctk` perspective.

**Comment by dlovell** [comment]
fixed with merge commit e89440bbd617e8034166687cf067c1f8f08cb556

testable with

```
import os
import ctk


dirname=os.path.split(ctk.__file__)[0]
with open(os.path.join(dirname, "../conf/ctk.conf")) as fh:
    print 'I can open conf/ctk.conf'
```
